import test from "node:test";
import assert from "node:assert/strict";
import { Item, Match, PriceRelation } from "../docs/js/models.js";
import { compare } from "../docs/js/comparator.js";
import { filterCandidates, Solver } from "../docs/js/solver.js";
const item = (values) => new Item(values);
test("comparator has Python's match, price, overlap and missing-value semantics", () => { const guess = item({ id: 1, name: "Guess", tradeable: true, price: 20, equipment_slot: "head", regions: ["A", "B"], categories: ["boss"], sources: ["one"] }); const answer = item({ id: 2, name: "Answer", tradeable: true, price: 10, equipment_slot: "body", regions: ["B"], categories: ["other"], sources: ["two"] }); const result = compare(guess, answer); assert.equal(result.tradeable, Match.MATCH); assert.equal(result.price, PriceRelation.LOWER); assert.equal(result.region, Match.MATCH); assert.equal(result.category, Match.NO_MATCH); assert.equal(compare(item({ name: "x", price: null }), item({ name: "y", price: 1 })).price, PriceRelation.EQUAL); });
test("filtering retains exactly candidates consistent with feedback", () => { const guess = item({ name: "G", tradeable: true, price: 20, regions: ["A"] }); const keep = item({ id: 1, name: "K", tradeable: true, price: 10, regions: ["A"] }); const reject = item({ id: 2, name: "R", tradeable: false, price: 10, regions: ["A"] }); assert.deepEqual(filterCandidates([keep, reject], guess, compare(guess, keep)).map((value) => value.id), [1]); });
test("opening guess is untradeable and unequippable; later guesses can trade", () => { const hard = item({ id: 1, name: "Hard", tradeable: false, equipment_slot: "-", sources: ["x"] }); const trade = item({ id: 2, name: "Trade", tradeable: true, price: 10, equipment_slot: "head", sources: ["y"] }); const solver = new Solver([hard, trade]); assert.equal(solver.recommendNextGuess()[0], hard); solver.applyFeedback(hard, compare(hard, trade)); assert.equal(solver.recommendNextGuess()[0], trade); });
